GET http://localhost:3000/

###
POST http://localhost:3000/register
Content-Type: application/json

{
    "email": "aldo1212lsm@gmail.com",
    "password": "123456",
    "role" : "1"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "kkiki6001@gmail.com",
    "password": "123456"
}

###
DELETE http://localhost:3000/logout

###
POST http://localhost:3000/data
Content-Type: application/json

 {
        "kode_tiang": "T005",
        "jenis_lampu": "back light",
        "gambar": "billboard3.jpg",
        "lat": "-6.917464", 
        "long": "107.619123",
        "jumlah_kendaraan": "4",
        "provinsi": "Jawa Barat",
        "kota": "Bandung",
        "kabupaten": "Bandung",
        "nama_jalan": "Jalan Pasteur",
        "ukuran": "10x6",
        "sisi": "1",
        "jenis": "billboard",
        "nama_pemilik": "PT. UVW",
        "status_sewa": "available"
    }

###
GET http://localhost:3000/data/billboard

###
GET http://localhost:3000/data

###
GET http://localhost:3000/data/id/9

###
PUT http://localhost:3000/data/id/10
Content-Type: application/json

{
        "kode_tiang": "T001",
        "jenis_lampu": "back light",
        "gambar": "billboard3.jpg",
        "lat": "-6.917464", 
        "long": "107.619123",
        "jumlah_kendaraan": "4",
        "provinsi": "Jawa Barat",
        "kota": "Bandung",
        "kabupaten": "Bandung",
        "nama_jalan": "Jalan Pasteur",
        "ukuran": "10x6",
        "sisi": "1",
        "jenis": "billboard",
        "nama_pemilik": "PT. UVW",
        "status_sewa": "available"
    }

###
POST http://localhost:3000/data/search/billboard


###
DELETE http://localhost:3000/data/id/1

###
POST http://localhost:3000/sewa
Content-Type: application/json

{
    "id_tiang"  : "3",
    "nama_penyewa" : "PT. XYZ",
    "lama_sewa" : "3",
    "satuan_sewa" : "bulan",
    "harga_sewa" : "1000000"
}
###
GET http://localhost:3000/sewa/3
###
GET http://localhost:3000/all

###
DELETE http://localhost:3000/sewa/3